
import React, { useState } from 'react';
import { getTransactions } from '../services/mockData';
import { TransactionType } from '../types';
import { PieChart, Download, Printer, Calendar } from 'lucide-react';

const Reports: React.FC = () => {
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  
  const handlePrint = () => {
    if(!fromDate || !toDate) {
        alert("Please select date range");
        return;
    }

    const txs = getTransactions();
    const start = new Date(fromDate);
    const end = new Date(toDate);
    
    // Filter
    const rangeTxs = txs.filter(t => {
        const d = new Date(t.date);
        return d >= start && d <= end;
    });

    const income = rangeTxs.filter(t => t.type === TransactionType.INCOME).reduce((sum, t) => sum + t.amount, 0);
    const expense = rangeTxs.filter(t => t.type === TransactionType.EXPENSE).reduce((sum, t) => sum + t.amount, 0);
    const net = income - expense;
    
    // Breakdown
    const expenseCats = rangeTxs.filter(t => t.type === TransactionType.EXPENSE).reduce((acc, t) => {
        const cat = t.expenseCategory || 'General';
        acc[cat] = (acc[cat] || 0) + t.amount;
        return acc;
    }, {} as Record<string, number>);

    const printWindow = window.open('', 'PRINT', 'height=800,width=800');
    if (!printWindow) return;

    printWindow.document.write(`
      <html>
        <head>
          <title>Profit & Loss Statement</title>
          <style>
            body { font-family: 'Helvetica Neue', Arial, sans-serif; padding: 40px; color: #333; }
            .header { text-align: center; border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 40px; }
            .h1 { font-size: 28px; font-weight: 900; margin: 0; }
            .dates { color: #666; font-size: 14px; margin-top: 10px; }
            .grid { display: flex; gap: 40px; margin-bottom: 40px; }
            .col { flex: 1; }
            .box { background: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 10px; }
            .label { font-size: 12px; text-transform: uppercase; letter-spacing: 1px; color: #888; font-weight: bold; }
            .val { font-size: 24px; font-weight: bold; margin-top: 5px; }
            .inc { color: #10b981; }
            .exp { color: #ef4444; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { text-align: left; border-bottom: 2px solid #eee; padding: 10px; font-size: 12px; text-transform: uppercase; }
            td { border-bottom: 1px solid #eee; padding: 10px; font-size: 14px; }
            .net-box { background: #1f2937; color: white; padding: 30px; border-radius: 12px; text-align: center; }
            @media print {
               body { -webkit-print-color-adjust: exact; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="h1">Profit & Loss Statement</div>
            <div class="dates">Period: ${fromDate} to ${toDate}</div>
          </div>

          <div class="grid">
              <div class="col">
                  <div class="box">
                      <div class="label">Total Revenue</div>
                      <div class="val inc">+ ${income.toLocaleString()} SAR</div>
                  </div>
              </div>
              <div class="col">
                  <div class="box">
                      <div class="label">Total Expenses</div>
                      <div class="val exp">- ${expense.toLocaleString()} SAR</div>
                  </div>
              </div>
          </div>

          <div class="net-box">
              <div class="label" style="color: #9ca3af;">Net Profit / Loss</div>
              <div class="val" style="font-size: 42px;">${net.toLocaleString()} SAR</div>
          </div>

          <h3 style="margin-top: 40px; border-bottom: 1px solid #eee; padding-bottom: 10px;">Expense Breakdown</h3>
          <table>
             <thead>
                <tr>
                   <th>Category</th>
                   <th style="text-align: right;">Amount</th>
                </tr>
             </thead>
             <tbody>
                ${Object.keys(expenseCats).map(k => `
                    <tr>
                        <td>${k}</td>
                        <td style="text-align: right;">${expenseCats[k].toLocaleString()}</td>
                    </tr>
                `).join('')}
             </tbody>
          </table>
          
          <div style="margin-top: 50px; text-align: center; font-size: 12px; color: #999;">
             Generated by Al-Amlak Property Manager
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 500);
  };

  return (
    <div className="bg-white rounded-3xl shadow-xl border border-slate-100 p-8 max-w-2xl mx-auto mt-10 animate-fadeIn">
        <div className="text-center mb-8">
            <div className="w-16 h-16 bg-slate-900 rounded-2xl flex items-center justify-center text-white mx-auto mb-4 shadow-xl shadow-slate-300">
                <PieChart size={32} />
            </div>
            <h2 className="text-2xl font-black text-slate-800">Generate Reports</h2>
            <p className="text-slate-500 font-medium">Create Profit & Loss Statements for print.</p>
        </div>

        <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100 space-y-6">
            <div className="grid grid-cols-2 gap-4">
                <div>
                    <label className="text-xs font-bold text-slate-400 uppercase tracking-wide mb-1 block">From Date</label>
                    <div className="relative">
                        <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} />
                        <input type="date" value={fromDate} onChange={e => setFromDate(e.target.value)} className="w-full pl-10 pr-3 py-2 border rounded-xl outline-none focus:ring-2 focus:ring-slate-400" />
                    </div>
                </div>
                <div>
                    <label className="text-xs font-bold text-slate-400 uppercase tracking-wide mb-1 block">To Date</label>
                    <div className="relative">
                        <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} />
                        <input type="date" value={toDate} onChange={e => setToDate(e.target.value)} className="w-full pl-10 pr-3 py-2 border rounded-xl outline-none focus:ring-2 focus:ring-slate-400" />
                    </div>
                </div>
            </div>

            <button 
                onClick={handlePrint}
                className="w-full py-4 bg-emerald-600 text-white font-bold rounded-xl hover:bg-emerald-700 transition-all shadow-xl shadow-emerald-200 flex items-center justify-center gap-3 transform hover:-translate-y-1"
            >
                <Printer size={20} /> Generate Statement
            </button>
        </div>
    </div>
  );
};

export default Reports;
